credentials:
  usernames:
    test:
      email: iamdenis46@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Test Account
      password: 1a2b3c # Will be hashed automatically
cookie:
  expiry_days: 30
  key: signature_key # Must be string
  name: cookie_name
pre-authorized:
  emails: 
  - iamdenis46@gmail.com